### ISSUE TITLE
策略组里面NeteaseMusic  选择解锁网易云后,app无网络

### ISSUE THREAD

**Issue by lxk0301** [nzw9314/Loon#1]
商店最新版本Loon,如图,策略组里面NeteaseMusic  选择解锁网易云后,app无网络,(解锁节点用的是Loon.conf里面自带的)
![image](https://user-images.githubusercontent.com/21308593/79545278-02130380-80c3-11ea-8f4d-fa6d3dd39ab8.png)

**Comment by nzw9314** [comment]
先确认网易云解锁证书是否安装.
不需要解锁时请选direct, 
另:配置里面的分享节点是公用的，可能不稳定
