### ISSUE TITLE
360.js 获取cookies 报错

### ISSUE THREAD

**Issue by Marcusias** [nzw9314/Loon#11]
脚本地址：https://github.com/nzw9314/QuantumultX/blob/master/Task/360.js

18 18:26:21 [Warn]   [JS exception]:ReferenceError: Can't find variable: $notify
18 18:26:31 [Warn]   [1167] evaluate script timeout!
18 18:26:38 [Warn]   [JS exception]:ReferenceError: Can't find variable: $notify
18 18:26:48 [Warn]   [1176] evaluate script timeout!
18 18:30:45 [Warn]   [JS exception]:ReferenceError: Can't find variable: $notify
18 18:30:55 [Warn]   [1432] evaluate script timeout!

**Comment by iepngs** [comment]
你不是在quanx里跑的吧 这个没做兼容
