### ISSUE TITLE
Task.conf里的移动查话费脚本地址错误

### ISSUE THREAD

**Issue by ddasddd** [nzw9314/Loon#19]
如题,应该是
`https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.fee.js`

**Comment by nzw9314** [comment]
> 如题,应该是
> 
> `https://raw.githubusercontent.com/chavyleung/scripts/master/10086/10086.fee.js`

已修正，我是照搬Chavy大佬10086.fee.cookie.js内注释的，所以他的脚本说明里面Loon的cron地址也有同样错误
