### ISSUE TITLE
去微信公众号底部广告好像不生效

### ISSUE THREAD

**Issue by ArmsZhou** [nzw9314/Loon#3]
引用地址
```plain
https://raw.githubusercontent.com/nzw9314/Loon/master/Script.conf
```
---

```js
# > 微信公众号
http-request ^https://mp\.weixin\.qq\.com/mp/getappmsgad script-path=https://Choler.github.io/Surge/Script/WeChat.js,tag=微信公众号广告
```
我怎么感觉应该是
```js
http-response ^https://mp\.weixin\.qq\.com/mp/getappmsgad script-path=https://Choler.github.io/Surge/Script/WeChat.js,tag=微信公众号广告
```

**Comment by xin510** [comment]
Thank you. Update in time!&nbsp;





------------------ 原始邮件 ------------------
发件人: nzw9314 <notifications@github.com&gt;
发送时间: 2020年4月30日 12:02
收件人: nzw9314/Loon <Loon@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[nzw9314/Loon] 去微信公众号底部广告好像不生效 (#3)





 
Closed #3.
