### ISSUE TITLE
优酷去广告

### ISSUE THREAD

**Issue by lvjiong** [nzw9314/Loon#9]
我的导入后，优酷还有广告，日志显示对应的域名已经reject了。
大家的优酷广告能过滤吗？

**Comment by xin510** [comment]
淘宝历史价格的是不是失效了？大佬能更新下吗？







------------------ 原始邮件 ------------------
发件人: lvjiong <notifications@github.com&gt;
发送时间: 2020年6月3日 12:55
收件人: nzw9314/Loon <Loon@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[nzw9314/Loon] 优酷去广告 (#9)





 
我的导入后，优酷还有广告，日志显示对应的域名已经reject了。
 大家的优酷广告能过滤吗？
